services:
  next:
    image: node:25-alpine
    container_name: softline_front
    working_dir: /app
    # command: sh -c "npm install && npm run dev"
    command: sh -c "npm run dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - softline-network

networks:
  softline-network:
    name: softline_softline-network
    external: true
